version: '2'
services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
